import Head from 'next/head'
import styles from '../styles/Home.module.css'
import '@aws-amplify/ui-react/styles.css';
import { useAuthenticator } from '@aws-amplify/ui-react';
import Link from 'next/link';

// ルートパス
const Index = () => {
  const { user, signOut } = useAuthenticator();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          {user.attributes?.email}
        </h1>
        <Link href="/blog">
          Blog
        </Link>
        <Link href="/user">
          存在しないページ
        </Link>
        <button onClick={() => signOut()}>Sign Out</button>
      </main>
    </div>
  )
}

export default Index;